---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wildsage/public_html/ 
    - bin/cp -R assets $DEPLOYPATH
    - bin/cp -R css $DEPLOYPATH
    - bin/cp -R js $DEPLOYPATH
    - bin/cp -R pages $DEPLOYPATH
    - bin/cp 404.html $DEPLOYPATH
    - bin/cp favicon.ico $DEPLOYPATH
    - bin/cp index.html $DEPLOYPATH
